name: KinD 03 - Ingress & HPA
on:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1.10.0
        with:
          node_image: kindest/node:v1.30.0
      - uses: azure/setup-kubectl@v4

      - name: Metrics Server (pin version)
        run: |
          set -euxo pipefail
          VERSION="v0.7.2"   # or v0.6.4

          # Install pinned release
          kubectl apply -f "https://github.com/kubernetes-sigs/metrics-server/releases/download/${VERSION}/components.yaml"

          # Patch args for KinD / CI (self-signed kubelet certs, internal IPs, node status port)
          kubectl -n kube-system patch deploy/metrics-server --type='json' -p='[
            {"op":"add","path":"/spec/template/spec/containers/0/args","value":[
              "--cert-dir=/tmp",
              "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname",
              "--kubelet-insecure-tls",
              "--kubelet-use-node-status-port"
            ]}
          ]' || true

          # In some CI networks the pod needs host networking to reach kubelets
          kubectl -n kube-system patch deploy/metrics-server --type='json' -p='[
            {"op":"add","path":"/spec/template/spec/hostNetwork","value":true},
            {"op":"add","path":"/spec/template/spec/dnsPolicy","value":"ClusterFirstWithHostNet"}
          ]' || true

          # Force a clean restart to avoid rolling-update deadlocks (replicas=1, maxUnavailable=0)
          kubectl -n kube-system scale deploy/metrics-server --replicas=0
          kubectl -n kube-system wait --for=delete pod -l k8s-app=metrics-server --timeout=120s || true
          kubectl -n kube-system scale deploy/metrics-server --replicas=1

          # Wait for readiness
          set +e
          kubectl -n kube-system rollout status deploy/metrics-server --timeout=300s
          rc=$?
          set -e

          # If rollout still fails, dump diagnostics before exiting
          if [ $rc -ne 0 ]; then
            echo '--- describe deploy ---'
            kubectl -n kube-system describe deploy/metrics-server || true
            echo '--- pod logs ---'
            kubectl -n kube-system logs deploy/metrics-server --all-containers --tail=-1 || true
            echo '--- apiservice status ---'
            kubectl get apiservice v1beta1.metrics.k8s.io -o yaml || true
            exit $rc
          fi

          # Ensure the aggregated API is available
          kubectl wait --for=condition=Available --timeout=180s apiservice/v1beta1.metrics.k8s.io

      - name: Ingress-NGINX
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl -n ingress-nginx rollout status deploy/ingress-nginx-controller --timeout=240s

      - name: Apply Manifests
        run: |
          IMG="ghcr.io/${{ github.repository }}"; TAG="sha-${{ github.sha }}"
          for f in k8s-kind-demos/03-ingress-and-hpa/k8s/*.yaml; do
            sed -i "s#ghcr.io/OWNER/REPO:sha-PLACEHOLDER#${IMG}:${TAG}#g" "$f" || true
          done
          kubectl apply -f k8s-kind-demos/03-ingress-and-hpa/k8s
          kubectl rollout status deploy/hello --timeout=240s

      - name: Generate Load
        run: |
          kubectl run load --rm -i --restart=Never --image=curlimages/curl --             sh -c 'for i in $(seq 1 200); do curl -s http://hello.default.svc.cluster.local/ > /dev/null; done'
          sleep 20
          kubectl get hpa
          kubectl get deploy hello -o wide
