name: KinD 01 - Deploy
on:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1.10.0
        with:
          config: k8s-kind-demos/01-kind-and-deploy/kind.yaml
      - uses: azure/setup-kubectl@v4
      - name: Swap image tag
        run: |
          IMG="ghcr.io/${{ github.repository }}"
          TAG="sha-${{ github.sha }}"
          sed -i "s#ghcr.io/OWNER/REPO:sha-PLACEHOLDER#${IMG}:${TAG}#g" k8s-kind-demos/01-kind-and-deploy/k8s/deployment.yaml
      - name: Apply
        run: kubectl apply -f k8s-kind-demos/01-kind-and-deploy/k8s/deployment.yaml
      - name: Wait Ready
        run: kubectl rollout status deploy/hello --timeout=180s
